<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\DeviceManagerFE.Application\DeviceManagerFE.Application.csproj" />
    <ProjectReference Include="..\DeviceManagerBE.Contracts\DeviceManagerBE.Contracts.csproj" />
    <ProjectReference Include="..\DeviceManagerFE.Contracts\DeviceManagerFE.Contracts.csproj" />
    <ProjectReference Include="..\DeviceManagerFE.Domain\DeviceManagerFE.Domain.csproj" />
    <ProjectReference Include="..\DeviceManagerFE.Infrastructure\DeviceManagerFE.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DeviceManagerFE</RootNamespace>
  </PropertyGroup>

</Project>

